!
! Tioga is a library for overset grid assembly on parallel distributed systems
! Copyright (C) 2015 Jay Sitaraman
!
!>
!> Test code to integrate TIOGA into CFD solver (Based on testTioga_dataRead.f90)
!> 
!> Gautham Bijoy
!>
!> 17/02/2026
!>
module run_tioga
  !
  use gridtype
  !
  implicit none
  !
  include 'mpif.h'
  !
  type(grid), target, allocatable :: gr(:)
  type(grid), pointer :: g
  integer :: myid,numprocs,ierr,nsave,runtime
  integer :: itime,ntimesteps,iter,nsubiter
  real*8 :: t0
  integer :: blockid
  logical :: iclip,exists
  integer :: ntypes, t
  integer :: nv1,nv2,nv3,ios1,ios2,rbase,ibase
  real*8 :: t1,t2
  integer :: i,n,m,ib,j,nblocks
  real*8 :: xt(3),rnorm
  integer :: dcount,fcount
  integer, allocatable :: receptorInfo(:),inode(:)
  real*8, allocatable :: frac(:)
  character*6 :: integer_string
  character*64 :: fname  
  character(len=20) :: t_str
  integer :: nc,nc_t                                ! Total number of cells - allocating iblank cell array
  integer, allocatable :: iblankcells(:), ibc(:)
  integer, allocatable :: iblanknodes(:)
  real(8), allocatable :: cellvals(:,:)
  
contains 

!--------------------------------------------------------------------------------------------
subroutine tioga_init_conn(input_dir)

character(len=*), intent(in) :: input_dir
integer :: offset2,tn,ib,i                           !offset counter for writing iblank nodes (mod8)
  !
  ! initialize mpi
  !
!  call mpi_init(ierr)
  call mpi_comm_rank(mpi_comm_world,myid,ierr)
  call mpi_comm_size(mpi_comm_world,numprocs,ierr)
  !
  ! read grid based on that generated by the
  ! strand/Cart generator
  !
  if (myid==0) write(6,*) '# tioga test on ',numprocs,' processes'
 
  nblocks=0
  exists=.true.
  do while(exists)
   write(integer_string,"(I6)") 100000+100*myid+nblocks
   fname=trim(input_dir)//'/flow'//trim(adjustl(integer_string(2:)))//'.dat'  ! Hardcoded inp address -> Input dir as env var
   !write(6,*) fname
   inquire(FILE=fname,EXIST=exists) 
   if (exists) nblocks=nblocks+1
  enddo
  !write(6,*) myid,nblocks
  allocate(gr(nblocks))
  do ib=1,nblocks
     write(integer_string,"(I6)") 100000+100*myid+ib-1
     fname=trim(input_dir)//'/flow'//trim(adjustl(integer_string(2:)))//'.dat' ! Hardcoded inp address -> Input dir as env var
     call readGrid_from_file(fname,gr(ib))
  enddo
  !
  if (myid==0) write(6,*) '# tioga test : finished reading grids '
  !
  ! initialize tioga
  !
  call tioga_init_f90(mpi_comm_world)
  call mpi_barrier(mpi_comm_world,ierr)
  !  
  ntypes=1
  nv1=6
  nv2=8
  nv3=4     !NUMBER OF VERTICES PER TET CELL
  do ib=1,nblocks
   g=>gr(ib)
   if (g%n6 > 0)  then
    call tioga_registergrid_data_mb(ib,g%bodytag(1),g%nv,g%x,g%iblank,g%nwbc,g%nobc,g%wbcnode,g%obcnode,&
       ntypes,nv1,g%n6,g%ndc6)
   else if (g%n8 > 0) then
    call tioga_registergrid_data_mb(ib,g%bodytag(1),g%nv,g%x,g%iblank,g%nwbc,g%nobc,g%wbcnode,g%obcnode,&
       ntypes,nv2,g%n8,g%ndc8)
   !-----------------------------------------------------------------------------------------------------
   !   REGISTERING TET FILE GRID DATA
   !
   else if (g%n4 > 0) then
    call tioga_registergrid_data_mb(ib,g%bodytag(1),g%nv,g%x,g%iblank,g%nwbc,g%nobc,g%wbcnode,g%obcnode,&
       ntypes,nv3,g%n4,g%ndc4)
   !
   !------------------------------------------------------------------------------------------------------
   endif
  enddo
  call tioga_preprocess_grids                  !< preprocess the grids (call again if dynamic) 
  call mpi_barrier(mpi_comm_world,ierr)
  write(t_str, '(I0)') t
  call cpu_time(t1)         
  call tioga_performconnectivity               !< determine iblanking and interpolation patterns
  call tioga_reduce_fringes()
  call cpu_time(t2)

tn = 0
do ib = 1, nblocks
  g => gr(ib)
  tn = tn + g%nv
end do
write(*,*)"tn = ",tn
if (.not. allocated(iblanknodes)) allocate(iblanknodes(tn))

offset2 = 0
do ib = 1, nblocks
  g => gr(ib)
  do i = 1, g%nv
    iblanknodes(offset2 + i) = g%iblank(i)
  end do
  offset2 = offset2 + g%nv
end do

open(unit=90, file='checking_nodes/tioga_node_iblank.dat', status='replace') !writing node iblank for diagnostics (mod7)
do ib = 1, nblocks
  g => gr(ib)
  do i = 1, g%nv
    write(90,*) i, g%iblank(i)
  end do
end do
close(90)

  call mpi_barrier(mpi_comm_world,ierr)
  if (myid==0) write(6,*) 'connectivity time=',t2-t1
 
!  call cpu_time(t1)
!  open(98,file='../build/driver/output/qvals_preinterp.dat',status='replace')
  do ib=1,nblocks
  g=>gr(ib)
  m=1
  do i=1,g%nv
     xt(:)=g%x(3*i-2:3*i)
          do n=1,g%nvar
       g%q(m)=(xt(1)+xt(2)+xt(3))
!       write(98,*) g%q(m)
       m=m+1
     enddo
  enddo
  enddo
!close(98)
  if (1==0) then
  do ib=1,nblocks
   call tioga_getdonorcount(ib,dcount,fcount)
   allocate(receptorInfo(4*dcount))
   allocate(inode(fcount),frac(fcount))
   !write(6,*) dcount,fcount
   !
   ! use this API if you need to interpolate the field variables yourself
   !
   call tioga_getdonorinfo(gr(ib)%bodytag(1),receptorInfo,inode,frac,dcount)
   !
   !> dcount = number of donors
   !> receptorInfo = {receptorProcess Id, receptor Index, receptor Block id, number of fractions}*dcount
   !> inode = indices for each receptor one group after the other
   !> frac  = weights for each receptor one group after the other
   !>
   m=0
   do i=1,dcount
    write(1000+myid,"(20(1x,I6))") ib,(inode(m+j),j=1,receptorInfo(4*i)+1),receptorInfo(4*i-3:4*i)
    m=m+(receptorInfo(4*i)+1)
   enddo 
   call flush(1000+myid)
   deallocate(receptorInfo,inode,frac)
  end do
  endif

 !---------- Writing Iblank Cell ---------------(mod5)  
nc_t = 0                             !Initialising total no. cells = 0, looping meshblocks to get total no.
do ib=1,nblocks
   g=>gr(ib)
   if (g%n6 > 0) then
      nc_t = nc_t + g%n6
   else if (g%n8 > 0) then
      nc_t = nc_t + g%n8
   else if (g%n4 > 0) then
      nc_t = nc_t + g%n4
   endif
enddo
allocate(iblankcells(nc_t))      

m = 1                                  
do ib=1,nblocks
   g=>gr(ib)
   if (allocated(ibc)) deallocate(ibc)
   if (g%n6 > 0) then
      allocate(ibc(g%n6))
      nc = g%n6
   else if (g%n8 > 0) then
      allocate(ibc(g%n8))
      nc = g%n8
   else if (g%n4 > 0) then
      allocate(ibc(g%n4))
      nc = g%n4
   endif
   call tioga_getiblank_cell(g%bodytag(1), ibc, nc)

   do i = 1,nc              
      iblankcells(m) = ibc(i)   
      m = m + 1
   enddo

   deallocate(ibc)
enddo

end subroutine tioga_init_conn

!----------------------------------------------------------------------------------------------------------

subroutine tioga_solutions(q_node, neq, nodes)
  real(8), intent(inout) :: q_node(:)
  integer, intent(in) :: neq,nodes
  integer :: k,mnode,m,i  
integer :: offset
character(len=64) :: finame
t=0


open(unit=88, file='checking_nodes/q_node_tioga_check.dat', status='replace')   !QNODE TESTING (mod5)
do i = 1, nodes
   WRITE(88,*) i, (q_node((i-1)*neq+k), k=1,neq)
enddo
close(88)
offset = 0
do ib=1,nblocks
   g=>gr(ib)
   call tioga_registersolution(g%bodytag(1), q_node(offset*neq+1:))
   offset = offset + g%nv
enddo
write(*,*)"(line 219) NEQ =",neq 
call cpu_time(t1)
call tioga_dataupdate_mb(neq, 'row')
open(99, file='checking_nodes/qvals_postinterp.dat', status='replace')  !checking q values post interp (mod5)
do i = 1, nodes
   write(99,*)i, (q_node((i-1)*neq+k), k=1,neq)
enddo
close(99)



!  do ib=1,nblocks
!    g=>gr(ib)
!    call tioga_registersolution(g%bodytag(1),q_node)
!  enddo
!  call tioga_dataupdate_mb(neq,'row')    !< update the q-variables (can be called anywhere)
                                             !< nvar = number of field variables per node
                                             !< if fields are different arrays, you can also 
                                             !< call this multiple times for each field
  call mpi_barrier(mpi_comm_world,ierr)
    call cpu_time(t2)
  if (myid==0) write(6,*) 'data update time=',t2-t1


write(*,*)"g%ncells",g%ncells

if (.not. allocated(cellvals)) allocate(cellvals(g%ncells,neq))         !Reconst. node vals put back into cell centred (pass to MPC)
cellvals=0.0
do i=1,g%ncells
  if (iblankcells(i)/=-1)CYCLE
    do k=1,neq
      cellvals(i,k)=0.0
        do m=1,4
          mnode = g%ndc4(m,i)
            cellvals(i,k) = cellvals(i,k) + q_node((mnode-1)*neq+k)
        enddo
      cellvals(i,k) = cellvals(i,k)/4.0                            !Simple avergaing - could be changed to weighted (mod8)
    enddo
enddo


  !
  ! compute error in interpolation
  ! should be machine-zero for the linear
  ! problem here
  ! 
  do ib=1,nblocks
   g=>gr(ib)
   m=1
   do i=1,g%nv
     xt(:)=g%x(3*i-2:3*i)
     do n=1,g%nvar
       rnorm=rnorm+(g%q(m)-(xt(1)+xt(2)+xt(3)))**2
       m=m+1
     enddo
   enddo
  enddo
  if (myid==0) write(6,"(A36)") '-- Interpolation error statistics --'
  if (myid==0) write(6,"(A15)") 'ProcId    Error'
  call flush(6)
  call mpi_barrier(mpi_comm_world,ierr)     ! global synchronisation point (all process must reach here b4 cont.)
  write(6,"(I4,3x,E15.7)") myid,sqrt(rnorm/g%nv/g%nvar)
  call mpi_barrier(mpi_comm_world,ierr)
!  call tioga_writeoutputfiles(g%nvar,'row',t) !< write output files, if need be
!  write(*,*) 'Moving block:', g%bodytag(1)
!  call movegrid(g)
end subroutine tioga_solutions

!---------------------------------------------------------------------------------------------------------------

subroutine tioga_fin()
  call mpi_barrier(mpi_comm_world,ierr)
  call tioga_delete
!  call mpi_finalize(ierr)
end subroutine tioga_fin
  !
end module run_tioga
